name: Windows RDP

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest

    steps:

      - name: Check Windows
        shell: powershell
        run: |
          Write-Host "OS:"
          Get-ComputerInfo | Select-Object WindowsProductName, WindowsVersion

      - name: Install Tailscale
        shell: powershell
        run: |
          Invoke-WebRequest `
            "https://pkgs.tailscale.com/stable/tailscale-setup-latest-amd64.msi" `
            -OutFile "$env:TEMP\tailscale.msi"

          Start-Process msiexec.exe `
            -ArgumentList "/i `"$env:TEMP\tailscale.msi`" /quiet /norestart" `
            -Wait

      - name: Connect Tailscale
        shell: powershell
        env:
          TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
        run: |
          $ts = "C:\Program Files\Tailscale\tailscale.exe"

          & $ts up `
            --auth-key="$env:TAILSCALE_AUTH_KEY" `
            --hostname="github-rdp"

      - name: Enable RDP
        shell: powershell
        run: |
          Set-ItemProperty `
            -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" `
            -Name "fDenyTSConnections" `
            -Value 0

          Set-ItemProperty `
            -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" `
            -Name "UserAuthentication" `
            -Value 1

          Enable-NetFirewallRule `
            -DisplayGroup "Remote Desktop"

      - name: Show Tailscale IP
        shell: powershell
        run: |
          $ts = "C:\Program Files\Tailscale\tailscale.exe"

          Write-Host "=============================="
          Write-Host "TAILSCALE IP"
          Write-Host "=============================="

          & $ts ip -4

          Write-Host ""
          Write-Host "RDP PORT: 3389"

      - name: Keep Alive
        shell: powershell
        run: |
          while ($true) {
            Write-Host "RDP RUNNING..."
            Start-Sleep -Seconds 60
          }
